---
title: "Replication of Study X by Sample & Sample (20xx, Psychological Science)"
author: "Replication Author[s] (contact information)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

Lee & Hawkins (2026) experimentally investigate the polarity preference in constituent questions (CQs) depending on the decision problem that the questioner aims to solve. They find that speakers prefer to use a CQ whose polarity matches that of the proposition whose truth would facilitate their goal, an effect mitigated by informativity and the structure of the decision problem. In this study, I apply Lee and Hawkins' experimental design to polar questions (PQs) in order to find out whether the same goal-polarity alignment persists in PQs as well as CQs (mitigated by informativity; decision structure does not apply). 


## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

(see below)

### Procedure	
Experiment 1: "Participants were told they were a scientist working with a rack of 10 vials, some of which were contaminated but visually indistinguishable from the uncontaminated vials. Rather than being explicitly given the percentage of contaminated vials, participants were told that 'only a few / half / most' of the vials were contaminated for the '20\% / 50\% / 80\%' base rate condition respectively. In the \emph{find uncontaminated} condition, their task was to select one vial to use for an experiment; in the \emph{find contaminated} condition, their task was to select one vial to examine and identify the contaminant. They could ask one question to a colleague who does not know the status of all the vials, but knows the status of some for certain. Three comprehension check questions were employed to ensure that participants understood their goal, the respondent's knowledge state, and the base rate condition. Data from participants who did not pass the comprehension checks were excluded.

On each trial, participants saw a visual representation of the vial rack, a proportion bar indicating the base rate of contamination (e.g., a bar with 20\% green and 80\% red in the 20\% base rate condition), and a goal card that reminded them of their goal without explicitly mentioning the word `contaminated' or `uncontaminated'.
They then completed the sentence ``Which vials are \underline{\hspace{1cm}}?'' by typing a word or a phrase. After the trial, participants were asked to report their strategy in deciding what question to ask. "
Exceptions: 
- Will pick out one vial to ask about
- Rather than being told that 'only a few / half / most' of the vials are contaminated, participants will be told that the vial is 'probably not / may or may not be / more likely than not' contaminated
- Visual representation will differ accordingly
- Participants will complete the sentence 'Is this vial [underline]?' by typing a word or a phrase, where they can choose to respond, e.g., 'contaminated', 'not comtaminated', 'clean', 'dirty', etc.

Experiment 2: "The scenario was similar to Experiment 1, with two key changes.
First, rather than completing a sentence, participants chose between two fully-formed questions: ``Which vials are contaminated?'' and ``Which vials are not contaminated?''
Second, we manipulated decision structure through the task framing.
In the \emph{singleton} conditions, participants were told they had to select a single vial---either to use for an experiment (find-uncontaminated) or to examine and identify the contaminant (find-contaminated).
In the \emph{set identification} conditions, participants were told they had to sort all vials into ``Safe to Use'' and ``Dispose'' bins.
To maintain goal alignment, participants in the find-uncontaminated condition learned that a colleague would use the ``Safe to Use'' vials for an important experiment, while participants in the find-contaminated condition learned that a safety inspector would examine the ``Dispose'' bin to verify proper handling.
Each participant completed a single trial, followed by a strategy probe question."

Exceptions:
- Participants will choose between 'Is this vial contaminated?' and 'Is this vial not contaminated?'.
- There will be no decision structure manipulation.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

The main difference is the type of question that the study investigates. The original study investigated CQs, and the participants were asked to freely complete a CQ in Exp1, and performed a forced choice task between two opposite polarity CQs in Exp2 in the original study. The present replication study will keep the same free completion/forced-choice structure, but with PQs.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
